stages:
  - deploy

deploy:
  stage: deploy
  script: 
    - "git pull origin $CI_COMMIT_REF_NAME"
    - "COMMIT_HASH=$(git rev-parse HEAD)"
    - "sudo cp -R /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/html/* /var/www/html/"
    - "echo \"Recent Commit Deployed: $COMMIT_HASH\""