stages:
  - pull

pull_changes:
  stage: pull
  image: alpine:latest  # Use an image that includes Git
  script:
    - apk add --no-cache git  # Install Git in the image
    - cd html
    - echo "Current working directory: $(pwd)"
    - git pull