stages:
  - build
  - docker
  - test

services:
  - docker:dind

build:
  stage: build
  only:
    - issue178
  script:
    - sudo vendor/bin/phpstan analyze /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/html/api
    - sudo vendor/bin/phpstan analyze /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/html/pages
    - sudo vendor/bin/phpstan analyze /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/html/Team104
    - sudo vendor/bin/phpstan analyze /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/html/index.php

# will need to add Dockers here for unit testing - add something here - temp - cache - trial

docker-job:
  stage: docker
  only:
    - issue178
  image: docker:dind
  script:
    - sudo docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - sudo docker build -t $CI_CD_SOCS_REGISTRY .
    - sudo docker push $CI_CD_SOCS_REGISTRY

test-job:
  stage: test
  only:
    - issue178
  image: $CI_CD_SOCS_REGISTRY
  script:
    - sudo docker run $CI_CD_SOCS_REGISTRY pytest -v 

    