stages:
  - deploy

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Testing the SSH connection..."
    - ssh cis3760f23-04.socs.uoguelph.ca "echo 'SSH test successful'"
    - echo "SSH test complete."
