stages:
  - build

variables:
  GIT_CLONE_PATH: "$CI_PROJECT_DIR/subfolder"

Build Application:
  stage: build
  script:
    - echo $GIT_CLONE_PATH
    - echo $CI_PROJECT_DIR
    - echo $CI_PROJECT_PATH
    - pwd
