
stages:
  - deploy

deploy:
  stage: deploy
  script:
    - sudo "git pull origin $CI_COMMIT_REF_NAME"
    - sudo "COMMIT_HASH=$(git rev-parse HEAD)"
    - sudo "COMMIT_MESSAGE=$(git log --format=%B -n 1 $COMMIT_HASH)"
    - sudo "CHANGES=$(git diff --name-only HEAD^..HEAD /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/html)"
    - >
      if [ -z "$CHANGES" ]; then
        echo "No changes in the HTML folder. Commit message: $COMMIT_MESSAGE" 
      else
        sudo chmod +w /var/www/html
        sudo cp -R /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/html/* /var/www/html/
        echo "Recent Commit Deployed: $COMMIT_HASH - $COMMIT_MESSAGE"
      fi
