stages:
  - deploy

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Testing the SSH connection..."
    - echo "The Git repository path is: $CI_PROJECT_DIR"
    - echo "Path test complete."
