stages:
  - deploy

deploy:
  stage: deploy
  only:
    - Sprint7
  before_script:
    - sudo -yq apt-get update
    - sudo apt-get -yqq install ssh
    - install -m 600 -D /dev/null ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - ssh-keyscan -H 131.104.49.95 >> ~/.ssh/known_hosts
  script:
    - echo "Executing the deployment script"
    - ssh socs@131.104.49.95 "cd /var/www/html/testing && git checkout Sprint7 && git pull && exit"
  after_script:
    - rm -rf ~/.ssh