image: debian:latest

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - Sprint7
  before_script:
    - whoami
    - ls -la /var/lib/apt/lists/
    - sudo apt-get update -qy
    - sudo apt-get install -yqq ssh
    - install -m 600 -D /dev/null ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - echo $SSH_HOST # debug here
    - ssh-keyscan -H 131.104.49.95 >> ~/.ssh/known_hosts

  script:
    - echo "Executing the deployment script"
    - ssh socs@$131.104.49.95 "cd /var/www/html/testing && git pull && exit"

  after_script:
    - rm -rf ~/.ssh