stages:
  - deploy #..
deploy:
  stage: deploy
  script: 
    - if [ "$CI_COMMIT_REF_NAME" == "Sprint7" ]; then cp -R /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/* /var/www/html/; fi