stages:
  - build

build:
  stage: build
  only:
    - issue178
  script:
    - if [ -d /tmp/phpstan/cache ]; then rm -rf /tmp/phpstan/cache/*; fi
    - sudo chmod +w /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/
    - sudo mkdir -p /tmp/phpstan/cache
    - sudo rm -rf /tmp/phpstan/cache/nette.configurator
    - sudo mkdir -p /tmp/phpstan/cache/nette.configurator
    - sudo chmod -R 777 /tmp/phpstan/cache
    - vendor/bin/phpstan analyze html/api
