image: debian:latest

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - Sprint7
  before_script:
    - sudo apt-get update -qy
    - sudo apt-get install -yqq ssh
    - mkdir -p /home/gitlab-runner/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d > /home/gitlab-runner/.ssh/id_rsa
    - chmod 600 /home/gitlab-runner/.ssh/id_rsa
    - cat /home/gitlab-runner/.ssh/id_rsa
    - ssh-keyscan -H 131.104.49.95 >> /home/gitlab-runner/.ssh/known_hosts

  script:
    - echo "Executing the deployment script"
    - ssh socs@131.104.49.95 "cd /var/www/html/testing && git checkout Sprint7 && git pull && exit"

  after_script:
    - rm -rf /home/gitlab-runner/.ssh
