
stages:
  - build

build:
  stage: build
  only:
    - issue178
  script:
  - vendor/bin/phpstan analyze /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/html/api &&
    vendor/bin/phpstan analyze /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/html/pages &&
    vendor/bin/phpstan analyze /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/html/Team104 &&
    vendor/bin/phpstan analyze /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/html/index.php

