stages:
  - build

build:
  stage: build
  only:
    - issue178
  script:
    - cd /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/
    - sudo /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/vendor/bin/phpstan analyze --no-cache /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/html/api