stages:
  - deploy
  - test
deploy:
  stage: deploy
  script:
    - "git pull origin $CI_COMMIT_REF_NAME"
    - "COMMIT_HASH=$(git rev-parse HEAD)"
    - "COMMIT_MESSAGE=$(git log --format=%B -n 1 $COMMIT_HASH)"
    - "CURRENT_BRANCH=$CI_COMMIT_REF_NAME"
    - "CHANGES=$(git diff --name-only HEAD^..HEAD /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/html)"

    - >
      if [ "$CURRENT_BRANCH" != "Sprint8" ]; then
        echo "Nothing occured on the Sprint9 branch. Deployment is skipped."
      elif [ -z "$CHANGES" ]; then
        echo "No changes in the HTML folder. Commit message: $COMMIT_MESSAGE" 
      else
        sudo chmod +w /var/www/html
        sudo cp -R /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/html/* /var/www/html/
        echo "Recent Commit Deployed: $COMMIT_HASH - $COMMIT_MESSAGE"
      fi

test:
  stage: test
  script: 
    - cd;cd ../../
    - cd /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/e2eTest
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install pytest-playwright
    - pip install pytest-playwright-visual
    - playwright install
    - pytest
