stages:
  - build

build:
  stage: build
  only:
    - issue178
  script:
    - cd /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/
    - sudo vendor/bin/phpstan analyze --no-progress /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/html/api
    - sudo vendor/bin/phpstan analyze --no-progress /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/html/pages
    - sudo vendor/bin/phpstan analyze --no-progress /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/html/Team104
    - sudo vendor/bin/phpstan analyze --no-progress /home/gitlab-runner/builds/wxi6sxsz/0/cis3760_f23/f23_cis3760_104/html/index.php
