stages:
  - deploy

deploy:
  stage: deploy
  only:
    - Sprint7
  before_script:
    - whoami
    - ls -la /var/lib/apt/lists/
    - apt-get -yq update #
    - apt-get -yqq install ssh #
    - install -m 600 -D /dev/null ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts

  script:
    - echo "Executing the deployment script"
    - ssh $SSH_USER@$SSH_HOST "cd /var/www/html/testing && git checkout Sprint7 && git pull && exit"

  after_script:
    - rm -rf ~/.ssh
