stages:
  - deploy

deploy:
  stage: deploy
  only:
    - Sprint7
  before_script:
    - sudo apt-get update -qy
    - sudo apt-get install -yqq ssh
    - mkdir -p $CI_PROJECT_DIR/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d > $CI_PROJECT_DIR/.ssh/id_rsa
    - chmod 600 $CI_PROJECT_DIR/.ssh/id_rsa
    - ssh-keyscan -H 131.104.49.95 > $CI_PROJECT_DIR/.ssh/known_hosts
    - chmod 644 $CI_PROJECT_DIR/.ssh/known_hosts

  script:
    - echo "Executing the deployment script"
    - ssh -o UserKnownHostsFile=$CI_PROJECT_DIR/.ssh/known_hosts socs@131.104.49.95 "cd /var/www/html/testing && git checkout Sprint7 && git pull && exit"

  after_script:
    - rm -rf $CI_PROJECT_DIR/.ssh