import re
from playwright.sync_api import Page, expect, sync_playwright

def test_navbar(page: Page):
    page.goto("https://cis3760f23-04.socs.uoguelph.ca")
    expect(page.get_by_text("F_23_CIS3760: Group_104")).to_be_visible()
    expect(page.get_by_role("link",name="Features")).to_be_visible()
    expect(page.get_by_role("link",name="Setup")).to_be_visible()
    expect(page.get_by_role("link",name="Using the Software")).to_be_visible()
    expect(page.get_by_role("link",name="Team")).to_be_visible()
    expect(page.get_by_role("link",name="Api Documentation")).to_be_visible()
    expect(page.get_by_text("104", exact=True)).to_be_visible()
    expect(page.get_by_text("F_23_CIS3760: Group_104")).to_be_visible()
    expect(page.get_by_text("Welcome to Group 104's PHP-powered homepage, where innovation and collaboration ")).to_be_visible()
    expect(page.get_by_text("Introducing VBA Induced Student Course Management Tool")).to_be_visible()
    page.get_by_role("link", name="Features").click()
    page.get_by_role("link", name="Setup").click()
    page.get_by_role("link", name="Using the Software").click()
    page.get_by_role("link", name="Team").click()
    page.get_by_role("link", name="Api Documentation").click()
    page.goto("https://cis3760f23-04.socs.uoguelph.ca")
    page.get_by_role("link", name="Api Frontend").click()
    page.goto("https://cis3760f23-04.socs.uoguelph.ca")

def test_getting_started(page: Page):
    page.goto("https://cis3760f23-04.socs.uoguelph.ca")
    page.get_by_role("link", name="Setup").click()
    expect(page.get_by_role("heading", name="Step 1: Download The Software")).to_be_visible()
    expect(page.locator("#setup").get_by_role("img").first).to_be_visible()
    expect(page.get_by_role("heading", name="Step 2: Enable Permissions")).to_be_visible()
    expect(page.locator("#setup").get_by_role("img").nth(1)).to_be_visible()
    expect(page.get_by_role("heading", name="Step 3: Open the excel workbook")).to_be_visible()
    expect(page.locator("#setup").get_by_role("img").nth(2)).to_be_visible()

def test_getting_start(page:Page):
    page.goto("https://cis3760f23-04.socs.uoguelph.ca")
    expect(page.get_by_role("link", name="Using the Software")).to_be_visible()
    expect(page.get_by_role("heading", name="Using The Software")).to_be_visible()
    expect(page.get_by_role("heading", name="Step 1: Enter Your Courses")).to_be_visible()
    expect(page.get_by_role("heading", name="Step 2: Generate & View The eligible courses")).to_be_visible()
    expect(page.get_by_role("heading", name="Step 3: Delete Unwanted Courses")).to_be_visible()
    expect(page.locator("#using").get_by_role("img").first).to_be_visible()
    expect(page.locator("#using").get_by_role("img").nth(1)).to_be_visible()
    expect(page.locator("#using").get_by_role("img").nth(2)).to_be_visible()


def test_Api_front_end_components(page:Page):
    page.goto("https://cis3760f23-04.socs.uoguelph.ca/pages/ApiFrontend/")
    expect(page.get_by_role("heading", name="Course Finder")).to_be_visible()
    expect(page.get_by_role("img", name="Person reading script")).to_be_visible()
    expect(page.get_by_role("heading", name="1. Enter your courses")).to_be_visible()
    expect(page.get_by_placeholder("Course code")).to_be_visible()
    expect(page.get_by_role("button", name="Enter")).to_be_visible()
    expect(page.get_by_role("columnheader", name="Course", exact=True)).to_be_visible()
    expect(page.get_by_role("button", name=" Filters")).to_be_visible()
    expect(page.get_by_role("button", name="SUBJECT")).to_be_visible()
    expect(page.get_by_role("button", name="LEVEL")).to_be_visible()
    expect(page.get_by_role("button", name="Apply")).to_be_visible()
    expect(page.get_by_role("button", name="Generate")).to_be_visible()
    expect(page.locator("#eligbleCoursesTableContainer")).to_be_visible()
    expect(page.get_by_role("columnheader", name="Restrictions")).to_be_visible()
    expect(page.get_by_role("columnheader", name="Course Code")).to_be_visible()
    expect(page.get_by_role("columnheader", name="Name")).to_be_visible()
    expect(page.get_by_role("columnheader", name="Description")).to_be_visible() 